# Generated by Django 5.2.1 on 2025-05-18 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('total_revenues', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_num', models.IntegerField()),
                ('table_status', models.CharField(max_length=10)),
                ('booth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.booth')),
            ],
        ),
    ]
