# Generated by Django 5.2.1 on 2025-05-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='부스 전용 QR 코드 이미지', null=True, upload_to='qr_codes/'),
        ),
    ]
