# Generated by Django 5.2.1 on 2025-05-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_booth_qr_code_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('booth_id', 'table_num')},
        ),
    ]
