# Generated by Django 5.2.1 on 2025-05-18 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_status', models.BooleanField(default=False)),
                ('total_price', models.IntegerField()),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.table')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=20)),
                ('menu_description', models.CharField(max_length=100)),
                ('menu_category', models.CharField(max_length=10)),
                ('menu_price', models.IntegerField()),
                ('menu_amount', models.IntegerField()),
                ('menu_remain', models.IntegerField()),
                ('menu_image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('booth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booth.booth')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_num', models.IntegerField()),
                ('order_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cart')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.menu')),
            ],
        ),
    ]
