# Generated by Django 5.2.1 on 2025-05-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_category',
            field=models.CharField(choices=[('음료', '음료'), ('메뉴', '메뉴')], max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_description',
            field=models.CharField(max_length=30),
        ),
    ]
