# Generated by Django 5.2.1 on 2025-05-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_menu_menu_category_alter_menu_menu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu_price',
            field=models.IntegerField(default=0),
        ),
    ]
