# Generated by Django 5.2.1 on 2025-05-18 22:43

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_menu_menu_category_alter_menu_menu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_image',
            field=models.ImageField(blank=True, null=True, upload_to=order.models.menu_image_upload_path),
        ),
    ]
