# Generated by Django 5.2.1 on 2025-05-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
