# Generated by Django 5.2.1 on 2025-05-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_menu_menu_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_category',
            field=models.CharField(choices=[('음료', '음료'), ('메뉴', '메뉴'), ('테이블 이용료', '테이블 이용료')], max_length=10),
        ),
    ]
