# Generated by Django 5.2.1 on 2025-05-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='menu_images/'),
        ),
    ]
