# Generated by Django 5.2.1 on 2025-05-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_menu_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fixed_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
