# Generated by Django 5.2.1 on 2025-05-18 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manager_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('table_num', models.IntegerField(default=0)),
                ('order_check_password', models.CharField(max_length=10)),
                ('account', models.CharField(max_length=30)),
                ('depositor', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=20)),
                ('seat_tax_person', models.IntegerField(blank=True, null=True)),
                ('seat_tax_table', models.IntegerField(null=True)),
                ('seat_type', models.CharField(choices=[('NO', 'No Seat Tax'), ('PP', 'Seat Tax Per Person'), ('PT', 'Seat Tax Per Table')], default='NO', max_length=2)),
                ('booth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='booth.booth')),
            ],
        ),
    ]
