# Generated by Django 5.2.1 on 2025-05-18 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_num', models.IntegerField(default=0)),
                ('order_check_password', models.CharField(max_length=8)),
                ('account', models.CharField(max_length=20)),
                ('depositor', models.CharField(max_length=10)),
                ('bank', models.CharField(max_length=10)),
                ('seat_tax_person', models.IntegerField(blank=True, null=True)),
                ('seat_tax_table', models.IntegerField(blank=True, null=True)),
                ('seat_type', models.CharField(choices=[('NO', 'No Seat Tax'), ('PP', 'Seat Tax Per Person'), ('PT', 'Seat Tax Per Table')], default='NO', max_length=2)),
                ('booth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='booth.booth')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
