# Generated by Django 5.2.1 on 2025-05-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='seat_tax_table',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
